### ISSUE TITLE
Calendar is not responsive on Ubuntu 20.04

### ISSUE THREAD

**Issue by ahsanf** [Fausto-Korpsvart/Big-Sur-StatusArea#12]
![image](https://user-images.githubusercontent.com/47440504/117176333-fbece380-adf9-11eb-9605-85e59f10be9d.png)

The problem just like that, can it be fixed ?

**Comment by LemonOrangeWasTaken** [comment]
I had the same problem, but the right side won't even show up.

**Comment by ahsanf** [comment]
> I had the same problem, but the right side won't even show up.

![image](https://user-images.githubusercontent.com/47440504/121530533-b8ece400-ca27-11eb-85fe-ea19c2be8e9c.png)
I have solved this issue, you can fix it locally with adding this code into  ~/.local/share/gnome-shell/extensions/BigSurStatusArea@korpsvart/stylesheet.css 
uncomment at  `.datemenu-calendar-column` 
and add this code : 
```css
.datemenu-calendar-column {
   height: auto;
   width: 22.0em; 
}
``
I think its worth to close this issue, because the repository owner discontinued this project #1

**Comment by LemonOrangeWasTaken** [comment]
Thank you that fixed it. Do you know how I can get that weather bar at the bottom?

**Comment by ahsanf** [comment]
> Thank you that fixed it. Do you know how I can get that weather bar at the bottom?

it's already in this extension, check this out https://www.pling.com/p/1427290/
