### ISSUE TITLE
Option to keep some panel items stock

### ISSUE THREAD

**Issue by ImDedInside-git** [Fausto-Korpsvart/Big-Sur-StatusArea#20]
Hey love your extension. Is there a way to use only the DATE and NOTIFICATION part and leave everything else stock since I want them to be separate?

**Comment by Fausto-Korpsvart** [comment]
> Hey love your extension. Is there a way to use only the DATE and NOTIFICATION part and leave everything else stock since I want them to be separate?

Hi, @ImDedInside-git, currently, @Ordissimo, maintains this extension, here is the repo that is kept up to date: https://github.com/Ordissimo/Big-Sur-StatusArea.

**Comment by ImDedInside-git** [comment]
thank you
