### ISSUE TITLE
No Display in Panel

### ISSUE THREAD

**Issue by Ordissimo** [Fausto-Korpsvart/Big-Sur-StatusArea#3]
Hi @Fausto-Korpsvart 
I'm a beginner with gnome-shell extensions, excuse me if I ask stupid questions :)
I would like to use your extension with the DashToPanel extension, but have the system menu replaced by your extension.
Do you have any idea where I should start?
Thanks

![Capture d’écran du 2021-03-12 11-18-34](https://user-images.githubusercontent.com/10682892/110926545-d1fcd080-8324-11eb-94d0-378b881a638c.png)

**Comment by Gasiyu** [comment]
What gnome version do you have? . Clone this repo and checkout #2 it will fixed the problem. Work's fine forme gnome 3.38.4 + dash to panel + this extension

**Comment by Ordissimo** [comment]
GNOME Shell 3.38.3, Thanks but #2 is my fix!

**Comment by Gasiyu** [comment]
> GNOME Shell 3.38.3, Thanks but #2 is my fix!

Sorry didn't see that, thanks for the fix. But dash to panel seems works fine for me
![image](https://user-images.githubusercontent.com/68300628/110933450-5d935300-835f-11eb-92d9-889b212f9f88.png)

**Comment by Ordissimo** [comment]
@Gasiyu ,No worries!
You are right, I need to keep the Dash visible and in this case it doesn't work well.
The problem is not with this extension but with DashToPanel.
Thanks 
I look to correct the date!
