### ISSUE TITLE
Differenciate User Indicator Icon from Power Off Icon

### ISSUE THREAD

**Issue by SaucySauce** [Fausto-Korpsvart/Big-Sur-StatusArea#6]
I guess this goes to https://github.com/Ordissimo/Big-Sur-StatusArea @Ordissimo

Right now, the Icon of the Indicator User, the weird settings icon, is also present as the Power Off. It also doesn't make much sense calling it _power_gicon, remnants from the original extensions, I guess.

**Comment by SaucySauce** [comment]
Edit: I'm currently doing a pull request and will be up shortly when the code is perfected.

**Comment by Ordissimo** [comment]
Le 2021-03-21 04:07, SaucySauce a écrit :
> Edit: I'm currently doing a pull request and will be up shortly when
> the code is perfected.

Hi @SaucySauce,
Only this extension is fully functional:
https://extensions.gnome.org/extension/4085/big-sur-status-area/ , and 
only in version 9 and 10.
I invite you to press the "Reset Indicators" button.
Finally if you want me to process your issues, you have to post them on 
the right git.

Thierry

**Comment by Ordissimo** [comment]
Le 2021-03-21 06:35, Thierry Huchard a écrit :
> Le 2021-03-21 04:07, SaucySauce a écrit :
>> Edit: I'm currently doing a pull request and will be up shortly when
>> the code is perfected.
> 
> Hi @SaucySauce,
> Only this extension is fully functional:
> https://extensions.gnome.org/extension/4085/big-sur-status-area/ , and
> only in version 9 and 10.
> I invite you to press the "Reset Indicators" button.
> Finally if you want me to process your issues, you have to post them
> on the right git.
> 

Issues were not active, sorry, this is corrected
