### ISSUE TITLE
Calendar layout issue

### ISSUE THREAD

**Issue by luca-martino** [Fausto-Korpsvart/Big-Sur-StatusArea#8]
On my Fedora 32/GNOME 3.36.8
![immagine](https://user-images.githubusercontent.com/17565704/112437110-e12d4680-8d46-11eb-96b9-23ff6a1d6fbc.png)

**Comment by Zany-Zachary1** [comment]
Same on Ubuntu 20.04 with GNOME 3.36

**Comment by Gasiyu** [comment]
Take a look on this fork https://github.com/Ordissimo/Big-Sur-StatusArea

**Comment by luca-martino** [comment]
> Take a look on this fork https://github.com/Ordissimo/Big-Sur-StatusArea

Upgraded to Fedora 33 and Gnome 3.38 then switched to Ordissimo-Big-Sur-StatusAreaUpgraded to Fedora 33 and Gnome 3.38
